In [1]:
import pandas as pd

In [2]:
order = pd.read_csv('elist订单表.csv')
order.head()

,ID,customer_ID,PURCHASE_TS,PRODUCT_ID,PRODUCT_NAME,USD_PRICE,PURCHASE_PLATFORM,MARKETING_CHANNEL,LOYALTY_PROGRAM
0,0001328c3c220830,2c06175e,2020/12/24,e682,Nintendo Switch,168.00,website,affiliate,0
1,0002af7a5c6100772,ee8e5bc2,2020/10/1,e682,Nintendo Switch,160.61,website,direct,0
2,0002b8350e167074,9eb4efe0,2020/4/21,8d0d,Nintendo Switch,151.20,website,direct,0
3,0006d06b98385729,cac7cbaf,2020/4/7,54ed,Sony PlayStation 5 Bundle,1132.82,website,direct,0
4,00097279a2f46150,6b0230bc,2020/11/24,8d0d,Nintendo Switch,33.89,website,direct,1

In [3]:
order.dtypes

ID                    object
customer_ID           object
PURCHASE_TS           object
PRODUCT_ID            object
PRODUCT_NAME          object
USD_PRICE            float64
PURCHASE_PLATFORM     object
MARKETING_CHANNEL     object
LOYALTY_PROGRAM        int64
dtype: object

In [4]:
order_status = pd.read_csv('elist订单状态表.csv')

In [6]:
order_status.dtypes

ORDER_ID       object
PURCHASE_TS    object
SHIP_TS        object
DELIVERY_TS    object
REFUND_TS      object
dtype: object

In [7]:
order_status.head()

            ORDER_ID PURCHASE_TS     SHIP_TS DELIVERY_TS  REFUND_TS
0   0001328c3c220830  2020/12/24  2020/12/13  2020/12/14        NaN
1  0002af7a5c6100772   2020/10/1   2020/9/21   2020/10/1        NaN
2   0002b8350e167074   2020/4/21   2020/2/16   2020/2/21        NaN
3   0006d06b98385729    2020/4/7    2020/4/4    2020/4/5  2022/4/28
4   00097279a2f46150  2020/11/24    2020/8/2    2020/8/5        NaN

In [8]:
order_status.isnull().sum()

ORDER_ID           0
PURCHASE_TS        0
SHIP_TS            0
DELIVERY_TS        0
REFUND_TS      18377
dtype: int64

In [ ]:
order_status['REFUND_TS'] = order_status['REFUND_TS'].replace('Missing value',pd.NA)

In [10]:
order_status.head()

            ORDER_ID PURCHASE_TS     SHIP_TS DELIVERY_TS  REFUND_TS
0   0001328c3c220830  2020/12/24  2020/12/13  2020/12/14        NaN
1  0002af7a5c6100772   2020/10/1   2020/9/21   2020/10/1        NaN
2   0002b8350e167074   2020/4/21   2020/2/16   2020/2/21        NaN
3   0006d06b98385729    2020/4/7    2020/4/4    2020/4/5  2022/4/28
4   00097279a2f46150  2020/11/24    2020/8/2    2020/8/5        NaN

In [11]:
order_status.to_csv('elist订单状态表.csv',index=False,encoding='utf-8')

In [12]:
customer = pd.read_csv('elist客户表.csv')

In [13]:
customer.dtypes

customer_id                 object
MARKETING_CHANNEL           object
ACCOUNT_CREATION_METHOD     object
LOYALTY_PROGRAM              int64
CREATED_ON                 float64
dtype: object

In [14]:
customer.head()

,customer_id,MARKETING_CHANNEL,ACCOUNT_CREATION_METHOD,LOYALTY_PROGRAM,CREATED_ON
0,2c06175e,affiliate,unknown,0,44109.0
1,ee8e5bc2,direct,desktop,0,43662.0
2,9eb4efe0,direct,desktop,0,43391.0
3,cac7cbaf,direct,desktop,0,43456.0
4,6b0230bc,direct,desktop,1,43753.0

In [16]:
customer.shape

(21864, 5)